export const AUTHENTICATED_START = "AUTHENTICATED_START";

export const REQUEST_START = "REQUEST_START";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const ADDED_ACCOUNT_SUCCESS = "ADDED_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_FAIL = "ADD_ACCOUNT_FAIL";

export const ADD_WHEAT_PURCHASE_SUCCESS = "ADD_WHEAT_PURCHASE_SUCCESS";
export const ADD_WHEAT_PURCHASE_FAIL = "ADD_WHEAT_PURCHASE_FAIL";

export const ADD_WHEAT_SALE_SUCCESS = "ADD_WHEAT_SALE_SUCCESS";
export const ADD_WHEAT_SALE_FAIL = "ADD_WHEAT_SALE_FAIL";

export const ADD_COTTON_PURCHASE_SUCCESS = "ADD_COTTON_PURCHASE_SUCCESS";
export const ADD_COTTON_PURCHASE_FAIL = "ADD_COTTON_PURCHASE_FAIL";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const ADD_GENERAL_VOUCHER_SUCCESS = "ADD_GENERAL_VOUCHER_SUCCESS";
export const ADD_GENERAL_VOUCHER_FAIL = "ADD_GENERAL_VOUCHER_FAIL";

export const ADD_COTTON_SALE_SUCCESS = "ADD_COTTON_SALE_SUCCESS";
export const ADD_COTTON_SALE_FAIL = "ADD_COTTON_SALE_FAIL";

export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

export const GET_ACCOUNTS_LIST_SUCCESS = "GET_ACCOUNTS_LIST_SUCCESS";
export const GET_ACCOUNTS_LIST_FAIL = "GET_ACCOUNTS_LIST_FAIL";

export const GET_BALANCE_SHEET_SUCCESS = "GET_BALANCE_SHEET_SUCCESS";
export const GET_BALANCE_SHEET_FAIL = "GET_BALANCE_SHEET_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const ADDGROUP_SUCCESS = "ADDGROUP_SUCCESS";
export const ADDGROUP_FAIL = "ADDGROUP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_IDEA_SUCCESS = "GET_IDEA_SUCCESS";
export const GET_IDEA_FAIL = "GET_IDEA_FAIL";

export const ADDED_IDEA_SUCCESS = "ADDED_IDEA_SUCCESS";
export const ADDED_IDEA_FAIL = "ADDED_IDEA_FAIL";

export const EDITED_IDEA_SUCCESS = "EDITED_IDEA_SUCCESS";
export const EDITED_IDEA_FAIL = "EDITED_IDEA_FAIL";

export const DELETE_IDEA_SUCCESS = "DELETE_IDEA_SUCCESS";
export const DELETE_IDEA_FAIL = "DELETE_IDEA_FAIL";

export const EDITED_PROFILE_SUCCESS = "EDITED_PROFILE_SUCCESS";
export const EDITED_PROFILE_FAIL = "EDITED_PROFILE_FAIL";

export const GET_SINGLE_IDEA_SUCCESS = "GET_SINGLE_IDEA_SUCCESS";
export const GET_SINGLE_IDEA_FAIL = "GET_SINGLE_IDEA_FAIL";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";

export const GET_INVESTORS_SUCCESS = "GET_INVESTORS_SUCCESS";
export const GET_INVESTORS_FAIL = "GET_INVESTORS_FAIL";

export const APPROVE_IDEA_SUCCESS = "APPROVE_IDEA_SUCCESS";
export const APPROVE_IDEA_FAIL = "APPROVE_IDEA_FAIL";

export const SET_PROFILE_STATUS = "SET_PROFILE_STATUS";
